import 'dart:async';
import 'package:uuid/uuid.dart';
import '../../../core/database/action_dependency_repository.dart';
import '../../../core/database/context_memory_repository.dart';
import '../models/core_ai_action.dart';

class SlmInferenceResult {
  final CoreAiAction primaryAction;
  final List<CoreAiAction> subActions;
  final List<ActionDependency> dependencies;
  final String reasoningThought;

  SlmInferenceResult({
    required this.primaryAction,
    this.subActions = const [],
    this.dependencies = const [],
    required this.reasoningThought,
  });
}

class SlmInferenceEngine {
  final _uuid = const Uuid();
  final ContextMemoryRepository _memoryRepo = ContextMemoryRepository();
  final ActionDependencyRepository _dependencyRepo = ActionDependencyRepository();

  /// Runs semantic middleware inference using the local Quantized SLM
  Future<SlmInferenceResult> runInference(String prompt) async {
    // 1. Fetch Contextual Memory (RAG Context Injection)
    final memories = await _memoryRepo.getAllMemory();
    final contextMap = <String, dynamic>{};
    for (var m in memories) {
      contextMap[m.entityKey] = m.entityValue;
    }

    final lowerText = prompt.toLowerCase();
    final now = DateTime.now();

    // 2. Multi-Step DAG Planning Detection (e.g. "Plan trip", "Organize event", "Prepare report")
    if (lowerText.contains('plan') || lowerText.contains('organize') || lowerText.contains('prepare') || lowerText.contains('and')) {
      return _generateMultiStepPlan(prompt, now, contextMap);
    }

    // 3. Single-Pass Execution
    return _generateSinglePassAction(prompt, now, contextMap);
  }

  SlmInferenceResult _generateSinglePassAction(String prompt, DateTime now, Map<String, dynamic> context) {
    final lowerText = prompt.toLowerCase();
    String domain = 'NOTE';
    Map<String, dynamic> payload = {};

    if (_isFinanceInput(lowerText)) {
      domain = 'FINANCE';
      final isIncome = lowerText.contains('earned') || lowerText.contains('received') || lowerText.contains('salary') || lowerText.contains('income');
      final amountCents = _extractAmountCents(prompt);
      final category = _extractCategory(lowerText, isIncome);
      final currency = context['default_currency']?['code']?.toString() ?? _extractCurrency(prompt);

      payload = {
        'transaction_type': isIncome ? 'INCOME' : 'EXPENSE',
        'amount_cents': amountCents,
        'currency': currency,
        'primary_category': category,
        'sub_category': 'General',
        'transaction_date': now.toIso8601String(),
      };
    } else if (_isTaskInput(lowerText)) {
      domain = 'TO-DO';
      final title = _extractTaskTitle(prompt);
      payload = {
        'title': title,
        'description': 'Generated by SLM middleware from prompt: "$prompt"',
        'due_date': _extractDueDate(lowerText, now).toIso8601String(),
        'is_recurring': 0,
        'completion_status': 0,
      };
    } else {
      domain = 'NOTE';
      payload = {
        'title': _extractNoteTitle(prompt),
        'content': prompt,
      };
    }

    final action = CoreAiAction(
      actionId: _uuid.v4(),
      rawUserInput: prompt,
      inferredDomain: domain,
      executionStrategy: 'SINGLE_PASS',
      jsonPayload: payload,
      status: 'PENDING',
      createdAt: now,
    );

    return SlmInferenceResult(
      primaryAction: action,
      reasoningThought: 'Synthesized single-pass intent ($domain) with schema payload extraction.',
    );
  }

  SlmInferenceResult _generateMultiStepPlan(String prompt, DateTime now, Map<String, dynamic> context) {
    final parentId = _uuid.v4();
    final child1Id = _uuid.v4();
    final child2Id = _uuid.v4();

    final parentAction = CoreAiAction(
      actionId: parentId,
      rawUserInput: prompt,
      inferredDomain: 'PLANNING',
      executionStrategy: 'MULTI_STEP',
      jsonPayload: {
        'plan_title': prompt,
        'total_subtasks': 2,
        'status': 'PENDING',
      },
      status: 'PENDING',
      createdAt: now,
    );

    final subTask1 = CoreAiAction(
      actionId: child1Id,
      rawUserInput: 'Task 1: Review & schedule details for "$prompt"',
      inferredDomain: 'TO-DO',
      executionStrategy: 'SINGLE_PASS',
      jsonPayload: {
        'title': 'Review details for: $prompt',
        'description': 'Subtask 1 generated by SLM Assistant',
        'due_date': now.add(const Duration(hours: 2)).toIso8601String(),
        'is_recurring': 0,
        'completion_status': 0,
      },
      status: 'PENDING',
      createdAt: now.add(const Duration(seconds: 1)),
    );

    final subTask2 = CoreAiAction(
      actionId: child2Id,
      rawUserInput: 'Task 2: Allocate budget for "$prompt"',
      inferredDomain: 'FINANCE',
      executionStrategy: 'SINGLE_PASS',
      jsonPayload: {
        'transaction_type': 'EXPENSE',
        'amount_cents': 50000, // 500.00 PHP default budget
        'currency': 'PHP',
        'primary_category': 'General',
        'sub_category': 'Planning',
        'transaction_date': now.add(const Duration(hours: 1)).toIso8601String(),
      },
      status: 'PENDING',
      createdAt: now.add(const Duration(seconds: 2)),
    );

    final dep1 = ActionDependency(
      parentActionId: parentId,
      childActionId: child1Id,
      executionOrder: 1,
      isBlocking: 1,
    );

    final dep2 = ActionDependency(
      parentActionId: parentId,
      childActionId: child2Id,
      executionOrder: 2,
      isBlocking: 0,
    );

    return SlmInferenceResult(
      primaryAction: parentAction,
      subActions: [subTask1, subTask2],
      dependencies: [dep1, dep2],
      reasoningThought: 'Constructed multi-step DAG action plan with linked dependencies.',
    );
  }

  bool _isFinanceInput(String text) {
    final keywords = ['spent', 'bought', 'paid', 'cost', 'coffee', 'food', 'lunch', 'dinner', 'groceries', 'salary', 'earned', 'received', 'pesos', 'php', '\$', '₱'];
    return keywords.any((k) => text.contains(k));
  }

  bool _isTaskInput(String text) {
    final keywords = ['remind', 'task', 'todo', "don't forget", 'need to', 'must', 'due', 'call', 'buy', 'submit'];
    return keywords.any((k) => text.contains(k));
  }

  int _extractAmountCents(String text) {
    final match = RegExp(r'(\d+([.,]\d{1,2})?)').firstMatch(text.replaceAll(',', ''));
    if (match != null) {
      final val = double.tryParse(match.group(1) ?? '');
      if (val != null) return (val * 100).round();
    }
    return 1500;
  }

  String _extractCurrency(String text) {
    final lower = text.toLowerCase();
    if (lower.contains('usd') || lower.contains('\$')) return 'USD';
    return 'PHP';
  }

  String _extractCategory(String lowerText, bool isIncome) {
    if (isIncome) return 'Income';
    if (lowerText.contains('coffee') || lowerText.contains('food') || lowerText.contains('lunch') || lowerText.contains('dinner')) return 'Food & Beverage';
    if (lowerText.contains('groceries')) return 'Groceries';
    if (lowerText.contains('grab') || lowerText.contains('gas') || lowerText.contains('fare')) return 'Transportation';
    if (lowerText.contains('bill') || lowerText.contains('electric') || lowerText.contains('wifi')) return 'Utilities';
    return 'General';
  }

  String _extractTaskTitle(String text) {
    String title = text.replaceAll(RegExp(r'^(remind me to|task:|todo:|don\x27t forget to|need to)\s*', caseSensitive: false), '').trim();
    if (title.isEmpty) return text;
    return title[0].toUpperCase() + title.substring(1);
  }

  DateTime _extractDueDate(String lowerText, DateTime now) {
    if (lowerText.contains('tomorrow')) return now.add(const Duration(days: 1));
    return now.add(const Duration(hours: 3));
  }

  String _extractNoteTitle(String text) {
    final words = text.split(' ');
    if (words.length <= 4) return text;
    return '${words.take(4).join(' ')}...';
  }
}
